[project]
name = "shubham-ubuntu-ai-agent"
version = "0.1.0"
description = "Helps me solve coding problems"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai==1.12.1",
    "python-dotenv==1.1.0",
]

[tool.uv.workspace]
members = [
    "Shubham_Ubuntu_AI_Agent",
]
